name: 3-tier-app-react-express-ci-cd

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd frontend && npm install

      - name: Come back
        run: |
          cd ..

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest frontend .

      - name: Build and tag backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest backend .

      - name: Push frontend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      - name: Push backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest .